version: "3"
services:
  web:
    build: .
    container_name: web-app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: nodemon -L server.js
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongo
    volumes:
      - data-volume:/data/db
    environment:
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
volumes:
  data-volume:
